Historial compras i ventas
UB-ES-2022-A2/LaVida-wallapopo pull request #226
Opened 2022-12-08 23:05 UTC by Maarc4

closes #199 #200 #201 #203 
Crear frontend y conectar a backend el historial de compras y de ventas.
Actualmente se accede a traves del dropdown de usuario.
Falta conectarlo a traves del menu lateral del perfil, pero eso lo hace @SirKaza .

2022-12-09 21:39 UTC, SirKaza commented
Falta arreglar front de selenium respecte a cambios hechos en esta branch, ahora me ocupare

2022-12-13 16:26 UTC, polcostaUB requested changes
El `HelloWorld.vue` tiene algunos paths de producción y otros de development

2022-12-14 00:15 UTC, SirKaza approved these changes

2022-12-14 07:23 UTC, polcostaUB requested changes
1. En la página de reviews, cuando el usuario no ha recibido ninguna reseña, en lugar de mostrar que no hay reviews (como en la de compras y ventas) se muestra la plantilla de las reviews:
![image](https://user-images.githubusercontent.com/61080733/207530257-2bda312b-7ae6-4aa8-a525-72acbb1a8ad4.png)

2. No pertenece a estas US, pero esta relacionado: En la página del perfil tenemos el botón "Opiniones" que por ahora no hace nada. Podemos quitarlo si ya tenemos otras formas de acceder a las reviews o darle funcionalidad.
![image](https://user-images.githubusercontent.com/61080733/207530668-21210f1e-ab67-4d75-b6ba-2c2485e895ed.png)

2022-12-14 09:43 UTC, polcostaUB approved these changes
nvm, acepto PR y ya se añadirán los cambios en la página de reviews más adelante

2022-12-14 09:43 UTC, merged