Us45.1-45.2-45.4  Ventana comprar producto
UB-ES-2022-A2/LaVida-wallapopo pull request #233
Opened 2022-12-11 19:52 UTC by MiguelUB

Importante el campo de Date debe ser "MM/YY" 
Para comprobar si una compra es exitosa o no se puede leer el contenido de la alerta dentro del modal que nos avisa de  si fue un exito o no la compra

Falta agregar un redireccionamiento a la pestaña de reviews se puede buscar con TODO en el componente ahi va el redireccionamento

Si se desea podemos cambiar el contenido del error igual al que nos mande back, por ahora solo dira Error

2022-12-11 19:54 UTC, MiguelUB commented
Mis cambios solo estan en el nuevo componente creado (buyProduct), product y store.js
En back solo toque 2 archivos de orders que Chang me indico

2022-12-11 23:12 UTC, MiguelUB commented
Tareas hechas #192 #193 #195

2022-12-14 08:01 UTC, polcostaUB requested changes
- @jorgec4444 Creo que el merge que hiciste con Development-Test ha roto cosas. En `HelloWorld.vue` hay links de producción donde debería haber links de dev. Además ahora la PR no pasa los tests de selenium que antes sí pasaba. Testead en local cualquier cambio a una rama antes de subirlo.
- @MiguelBCN Los cambios en la navbar (botones del perfil y subir producto) creo que no se está mostrando como deberían.
![image](https://user-images.githubusercontent.com/61080733/207537170-f98a27e1-0412-4808-a596-5f1c3f17d1e0.png)
- Al comprar se permite que el campo correspondiente "Propietario de Tarjeta" esté formado por números. También se permite que la fecha del campo "Date" sea una fecha anterior a la actual, por lo que técnicamente estamos permitiendo usar tarjetas caducadas. Sugiero cambiar "Date" por "Fecha de caducidad" o algo similar (consistencia en el idioma y mayor claridad de lo que se requiere en el campo)

2022-12-15 11:06 UTC, polcostaUB commented
Mergeado con US45.5-US50.1, integramos sistemas de compras y reseñas juntos

2022-12-15 11:06 UTC, closed without merging