Fav button created
UB-ES-2022-A2/LaVida-wallapopo pull request #79
Opened 2022-10-28 15:22 UTC by jorgec4444

Fav button created in every product card with a little animation when clicking. (Done but still improvable in future).

2022-10-28 16:01 UTC, polcostaUB requested changes
La imagen `logo_favorito.png` no está en **assets**

2022-10-29 02:50 UTC, jorgec4444 commented on frontend/src/components/CardProduct.vue
> +              <img class="fav-img" src="../assets/logo_favorito.png" width="24px" height="24px" alt="don't load">
Fixed.

2022-10-29 11:46 UTC, polcostaUB reviewed
El botón con la imagen y la animación se muestran correctamente. 
Solo una duda: La lógica para cambiar de corazón vacío a corazón lleno se corresponde a otra tarea? @jorgec4444

2022-10-29 11:56 UTC, jorgec4444 commented
Sí, de momento solamente había que tener un botón para guardar el estado de favorito pero habrá una futura tarea para que sea de la forma que dices.

2022-10-29 11:58 UTC, polcostaUB approved these changes
Perfecto, todo en orden entonces

2022-10-29 11:58 UTC, merged