US22 - Unit testing
UB-ES-2022-A2/LaVida-wallapopo pull request #97
Opened 2022-11-02 18:10 UTC by polcostaUB

Tests unitarios y funcionales de los modelos y resources

2022-11-02 23:42 UTC, chyeyexx7 requested changes
A parte del pequeño problema que he tenido al no poner `json=json` en post, el resto en principio funciona bien, excepto los tests donde se le envía `None` en alguno de los campos requeridos. El `Reqparse` con `required=True` parece que no es capaz de tratar con los `None` por defecto. Esto creo que lo podríamos tener para una tasca futura, o modificar todas las APIs actuales.

2022-11-02 23:42 UTC, chyeyexx7 commented on tests/functional/test_accounts.py
> +        login = requests.post(url + "API/login", json)
Por alguna razón no me funciona esto. No sé si es por la versión de requests, pero para que funcione he tenido que añadir json=json en post.

2022-11-02 23:42 UTC, chyeyexx7 commented on tests/functional/test_accounts.py
> +        login = requests.post(url + "API/login", json)
```suggestion
        login = requests.post(url + "API/login", json=json)
```

2022-11-02 23:42 UTC, chyeyexx7 commented on tests/functional/test_accounts.py
> +        requests.post(url + "API/login", json)
```suggestion
        requests.post(url + "API/login", json=json)

2022-11-02 23:42 UTC, chyeyexx7 commented on tests/functional/test_accounts.py
> +    json = "{'username': 'dummyname', 'email': None, 'password': 'dummy12.'}"
El formato del json es un string...
```suggestion
    json = {'username': 'dummyname', 'email': None, 'password': 'dummy12.'}

2022-11-02 23:42 UTC, chyeyexx7 commented on tests/functional/test_accounts.py
> +    account = requests.post(url + "API/account", json)
```suggestion
    account = requests.post(url + "API/account", json=json)

2022-11-02 23:42 UTC, chyeyexx7 commented on tests/functional/test_accounts.py
> +    assert account.status_code == 400
En este caso devolvería un status_code 500, ya que de la forma que está hecho la API no se contempla los None. Se podría modificar para un futuro y que controle los None en los campos requeridos.
```suggestion
    assert account.status_code == 500

2022-11-02 23:42 UTC, chyeyexx7 commented on tests/functional/test_accounts.py
> +    assert account.json() == {'message': {'email': 'This field cannot be left blank'}}
```suggestion
    assert account.json() == {'message': 'Internal Server Error'}

2022-11-02 23:42 UTC, chyeyexx7 commented on tests/functional/test_accounts.py
> +    json = {'username': None, 'email': 'dummy@gmail.com', 'password': 'dummy12.'}
Mismo caso que antes, no se contempla el caso del None por ahora...

2022-11-02 23:42 UTC, chyeyexx7 commented on tests/functional/test_products.py
> +    r = requests.post(url + "API/catalog/add/pepe432@gmail.com", auth=user_auth)
Esto no funciona ya que en el post hay que poner explícitamente el body. 
```suggestion
    r = requests.post(url + "API/catalog/add/pepe432@gmail.com", json=json, auth=user_auth)

2022-11-03 07:25 UTC, polcostaUB commented on tests/functional/test_accounts.py
> +        login = requests.post(url + "API/login", json)
Puede que sea por la versión de `requests`, porque he intentado cambiar de versión y me han salido errores que antes no aparecían. Ahora deberían estar todos los posts con el `json=json`.

2022-11-03 07:28 UTC, polcostaUB commented on tests/functional/test_accounts.py
> +    json = "{'username': 'dummyname', 'email': None, 'password': 'dummy12.'}"
Por algún motivo no me pillaba el json correctamente sin las comillas y lo dejé así. Ya está corregido.

2022-11-03 07:32 UTC, polcostaUB commented on tests/functional/test_products.py
> +    r = requests.post(url + "API/catalog/add/pepe432@gmail.com", auth=user_auth)
Creo que esto también está relacionado con la versión del `requests` ya que no me daba ningún problema y hacía el assert correctamente. Ya está cambiado.

2022-11-03 09:49 UTC, chyeyexx7 requested changes
En `conftest.py` sigue petando por esta esta función:
```
@pytest.fixture(scope='function')
def user_auth():
    json = {'email': 'pepe432@gmail.com', 'password': 'pepe123,.'}
    login = requests.post("http://localhost:5000/API/login", json)    # <-----
    token = login.json()
    auth = HTTPBasicAuth(token['token'], '')
    return auth
```
Creo que es lo último que falta, aunque es posible que haya conflictos con mi PR ya que se ha tenido que modificar la base de datos para cumplir alguno de los US.

Si quieres lo puedo modificar yo (la parte de actualizar json de products) por la tarde cuando me ponga.

2022-11-03 17:36 UTC, computingcreeper reviewed
Todo me parece bien, además se ha actualizado la PR con los cambios sugeridos por Chang, perfecto. Aun así me falla el tema del account.json() y no tengo claro el motivo.

2022-11-03 17:36 UTC, computingcreeper commented on tests/functional/test_accounts.py
> +    assert account.json() == {'message': 'Internal Server Error'}
En esta línea parece que no hay un mensaje JSON en account, por lo que salta error al llamar a account.json(). Solo me falla este caso concreto, ya que otras llamadas a la misma función funcionan correctamente.

2022-11-03 20:39 UTC, polcostaUB commented
He dejado el `json()` de `products.py` como `'username': AccountsModel.get_by_email(self.user_id).json()['username']`. 
No se si de algún problema con algo fuera de los tests ahora mismo.

2022-11-03 21:14 UTC, chyeyexx7 requested changes
En principio funciona todo menos el problema de la columna `confirmed` de accounts.

2022-11-03 21:14 UTC, chyeyexx7 commented on tests/unit/test_model_accounts.py
> +    expected = {'email': 'dummy@gmail.com', 'username': 'dummyname', 'name': None, 'surname': None, 'birthday': None, 'is_admin': 0}
Falta el confirmed y añadir desde accounts.json() el return confirned, ya que he visto que en otro test de account esperas un output de confirmed

2022-11-03 21:32 UTC, polcostaUB commented
Ya debería estar, lo de accounts se me pasó porque no me daba ningún error

2022-11-03 22:59 UTC, chyeyexx7 approved these changes
Todo correcto, ha podido pasar todos los tests

2022-11-03 22:59 UTC, merged